### ISSUE TITLE
Kinds

### ISSUE THREAD

**Issue by jamiebuilds** [zaptst/zap#7]
Right now there are three "kinds" of events in ZAP:

> - `"suite"` A group of tests or other suites
> - `"test"` An individual test case containing assertions
> - `"assertion"` An individual bit of logic that passes or fails.

These names seem pretty test-framework centric and don't clearly map to other types of tools like linters or type checkers.

I want to play around with different ideas for names, like the following:

- `"group"`
- `"item"`
- `"check"`

Where a testing framework might look like this:

```yaml
- item: Test
    - check: Assertion
- group: Suite
  - item: Test
    - check: Assertion
    - check: Assertion
  - item: Test
    - check: Assertion
  - group: Nested Suite
    - item: Test
      - check: Assertion
      - check: Assertion
      - check: Assertion
```

And a linter might look like this:

```yaml
- group: File
  - check: Lint Error
  - check: Lint Error
  - check: Lint Error
- group: File
  - check: Lint Error
  - check: Lint Error
  - check: Lint Error
```

And a type checker might look like this:

```yaml
- check: Type Error
- check: Type Error
- check: Type Error
- check: Type Error
- check: Type Error
- check: Type Error
```

There's also the potential that there is actually no need for a `"kind"` and the tree structure alone is enough.
